
// 검색
// q, order = 'date' | 'price_asc' | 'price_desc', version = '4' 
export const api2 = 'https://api.stg-bunjang.co.kr/api/1/find_v2.json';

// 자동 완성
// q, type = 'product', v = '2'
export const api1 = 'https://api.stg-bunjang.co.kr/api/1/search/suggests_keyword.json';



// 검색 response (키워드: 신)
const search_res = 
{
  "result": "success",
  "no_result": false,
  "no_result_type": null,
  "no_result_message": null,
  "ad_more_info": false,
  "ad_products": [
  ],
  "list": [
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 강남구 신사동",
      "max_cpc": null,
      "name": "테스트 상품아 필요해 22",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "2000002660",
      "price": "2649000",
      "product_image": "https://media.stg-bunjang.co.kr/product/2000002660_1_1607952334_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "128962",
      "update_time": 1607952334,
      "used": 13,
      "imp_id": "99a55fdaed9b000006d8",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 강남구 신사동",
      "max_cpc": null,
      "name": "테스트 상품이 필요해",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "2000002659",
      "price": "264000",
      "product_image": "https://media.stg-bunjang.co.kr/product/2000002659_1_1607952280_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "128962",
      "update_time": 1607952280,
      "used": 13,
      "imp_id": "99a55fdaed9b000006d9",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": true,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "담배 칼 병신 술 애완 에어팟",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "2000001491",
      "price": "0",
      "product_image": "https://media.stg-bunjang.co.kr/product/2000001491_1_1605681388_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "2420074",
      "update_time": 1603878262,
      "used": 13,
      "imp_id": "99a55fdaed9b000006da",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신기한 키보드-2",
      "num_comment": "1",
      "num_faved": "1",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "2000001183",
      "price": "50000",
      "product_image": "https://media.stg-bunjang.co.kr/product/2000001183_1_1603764223_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "1",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "9145992",
      "update_time": 1602572416,
      "used": 13,
      "imp_id": "99a55fdaed9b000006db",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": true,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신발아아아",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "2000001108",
      "price": "0",
      "product_image": "https://media.stg-bunjang.co.kr/product/2000001108_1_1596437161_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "2000002194",
      "update_time": 1598494709,
      "used": 13,
      "imp_id": "99a55fdaed9b000006dc",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신용카 드현금서비스",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "2000001145",
      "price": "5000",
      "product_image": "https://media.stg-bunjang.co.kr/product/2000001145_1_1597201231_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "2000001658",
      "update_time": 1597201213,
      "used": 13,
      "imp_id": "99a55fdaed9b000006dd",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신용카드현금화",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "2000001144",
      "price": "1255",
      "product_image": "https://media.stg-bunjang.co.kr/product/2000001144_1_1597200347_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "2000001658",
      "update_time": 1597200347,
      "used": 13,
      "imp_id": "99a55fdaed9b000006de",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신용카드현금화",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "2000001143",
      "price": "5000",
      "product_image": "https://media.stg-bunjang.co.kr/product/2000001143_1_1597200085_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "2000001658",
      "update_time": 1597200072,
      "used": 13,
      "imp_id": "99a55fdaed9b000006df",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신용카드현금화",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "2000001142",
      "price": "1500",
      "product_image": "https://media.stg-bunjang.co.kr/product/2000001142_1_1597200021_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "2000001658",
      "update_time": 1597199760,
      "used": 13,
      "imp_id": "99a55fdaed9b000006e0",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": true,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "자신감 음료",
      "num_comment": "0",
      "num_faved": "1",
      "only_neighborhood": true,
      "outlink_url": "",
      "pid": "2000000346",
      "price": "3000",
      "product_image": "https://media.stg-bunjang.co.kr/product/2000000346_1_1583744671_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "음료",
      "uid": "7602598",
      "update_time": 1583722808,
      "used": 13,
      "imp_id": "99a55fdaed9b000006e1",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "✔[2020•봄신상/BEST] #심쿵심쿵 잇츠 플라워 체인크로스 원핸들",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115369856",
      "price": "45000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115369856_1_1578990494_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "38044",
      "update_time": 1578990494,
      "used": 2,
      "imp_id": "99a55fdaed9b000006e2",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": true,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "리복 인스타펌프 퓨리 새신발 275mm 팝니다.",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115047347",
      "price": "90000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115047347_1_1578523808_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "리복 인스타펌프퓨리 275mm",
      "uid": "5893419",
      "update_time": 1578546775,
      "used": 2,
      "imp_id": "99a55fdaed9b000006e3",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": true,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "스노우보드 신발 디럭스 부츠 18/19",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115043016",
      "price": "90000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115043016_1_1578503423_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "7769790",
      "update_time": 1578543216,
      "used": 13,
      "imp_id": "99a55fdaed9b000006e4",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "파나소닉 루믹스G 20mm f1.7신형",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115046676",
      "price": "150000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115046676_1_1578519218_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "4248267",
      "update_time": 1578539786,
      "used": 13,
      "imp_id": "99a55fdaed9b000006e5",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": true,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "(무배)새책 해커스 2020최신개정판 LC/ 중급 RC 싸게 팝니다",
      "num_comment": "0",
      "num_faved": "2",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115044460",
      "price": "10000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115044460_1_1578539431_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "해커스토익LC 해커스토익중급 최신개정판 해커스토익RC 해커스리스닝",
      "uid": "2268237",
      "update_time": 1578539259,
      "used": 2,
      "imp_id": "99a55fdaed9b000006e6",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신한 터치 트윈마카 60색 A세트",
      "num_comment": "0",
      "num_faved": "2",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115045318",
      "price": "100000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115045318_1_1578509965_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "트윈마카  신한터치트윈마카 트윈마카60색 60색a세트",
      "uid": "6045972",
      "update_time": 1578534521,
      "used": 13,
      "imp_id": "99a55fdaed9b000006e7",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": true,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "슈퍼미니프라 초룡신 미조립",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115051279",
      "price": "40000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115051279_1_1578533455_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "가오가이거 초룡신 슈퍼미니프라",
      "uid": "2452062",
      "update_time": 1578533368,
      "used": 13,
      "imp_id": "99a55fdaed9b000006e8",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "톰보이코트 팝니다 (신상)",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115051136",
      "price": "260000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115051136_1_1578533458_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "s 66 77",
      "uid": "2864633",
      "update_time": 1578533158,
      "used": 2,
      "imp_id": "99a55fdaed9b000006e9",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "디스퀘어드 정품 선글라스 (신품급)",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115050869",
      "price": "149000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115050869_1_1578532731_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "디스퀘어드 디스퀘어드선글라스 명품선글래스",
      "uid": "8340552",
      "update_time": 1578532719,
      "used": 13,
      "imp_id": "99a55fdaed9b000006ea",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신발,가방,잡화> 지갑,벨트",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115050493",
      "price": "400000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115050493_1_1578532082_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "11",
      "uid": "734566",
      "update_time": 1578532071,
      "used": 13,
      "imp_id": "99a55fdaed9b000006eb",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "무신사 스토어 감사 쿠폰",
      "num_comment": "0",
      "num_faved": "1",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115050303",
      "price": "1000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115050303_1_1578531721_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "무신사쿠폰 무신사 musinsa",
      "uid": "9291567",
      "update_time": 1578531702,
      "used": 2,
      "imp_id": "99a55fdaed9b000006ec",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": true,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "갤럭시S9 S급 2대 사요 통신사 상관없음",
      "num_comment": "0",
      "num_faved": "1",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115049817",
      "price": "440000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115049817_1_1578530827_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "갤럭시s9",
      "uid": "1810096",
      "update_time": 1578530811,
      "used": 13,
      "imp_id": "99a55fdaed9b000006ed",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "#폴스부띠끄테디백 #f/w신상",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115049668",
      "price": "88000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115049668_1_1578530745_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "폴스부띠끄 폴스부띠끄테디백 미니백 크로스백 신상백",
      "uid": "4334237",
      "update_time": 1578530533,
      "used": 2,
      "imp_id": "99a55fdaed9b000006ee",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "(신품급)로지텍 mx-510",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115049334",
      "price": "40000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115049334_1_1578529874_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "로지텍mx-510",
      "uid": "83703",
      "update_time": 1578529874,
      "used": 13,
      "imp_id": "99a55fdaed9b000006ef",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": true,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "[정품]루이비통 신상 패스트레인 스니커즈 250-255",
      "num_comment": "0",
      "num_faved": "1",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115048823",
      "price": "800000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115048823_1_1578528833_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "루이비통 명품 스니커즈 250 새상품",
      "uid": "178943",
      "update_time": 1578528851,
      "used": 2,
      "imp_id": "99a55fdaed9b000006f0",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "아이러니 런닝머신",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115047796",
      "price": "800000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115047796_1_1578525939_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "215360",
      "update_time": 1578525709,
      "used": 13,
      "imp_id": "99a55fdaed9b000006f1",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": true,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "바고보 일본브랜드 메신져백",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115047384",
      "price": "90000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115047384_1_1578524004_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "bagoboo 메신져",
      "uid": "3469981",
      "update_time": 1578524004,
      "used": 13,
      "imp_id": "99a55fdaed9b000006f2",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "구두 로퍼 신발 검정 250",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115046661",
      "price": "20000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115046661_1_1578519172_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "로퍼 구두 신발 스웨이드",
      "uid": "4159634",
      "update_time": 1578519117,
      "used": 13,
      "imp_id": "99a55fdaed9b000006f3",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "겨울 아동신발",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115045028",
      "price": "26500",
      "product_image": "https://media.stg-bunjang.co.kr/product/115045028_1_1578509833_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "털부츠 아동부츠 아동스니커즈",
      "uid": "32006",
      "update_time": 1578514596,
      "used": 2,
      "imp_id": "99a55fdaed9b000006f4",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신기한 한글나라 3세트",
      "num_comment": "0",
      "num_faved": "1",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115045527",
      "price": "50000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115045527_1_1578511162_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "한솔학습지 신기한한글나라",
      "uid": "4147706",
      "update_time": 1578511162,
      "used": 2,
      "imp_id": "99a55fdaed9b000006f5",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": true,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "닌텐도 스위치용 외장하드 판매.(최신 한글패치 업데이트2019.1.9)",
      "num_comment": "1",
      "num_faved": "1",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115045008",
      "price": "5000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115045008_1_1578549998_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "스위치게임 닌텐도게임 외장하드1테라 외장하드2테라 외장하드3테라",
      "uid": "9639682",
      "update_time": 1578510444,
      "used": 2,
      "imp_id": "99a55fdaed9b000006f6",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "늑대와 향신료 크리스마스 한정판 키링 판매합니다.",
      "num_comment": "0",
      "num_faved": "1",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115045285",
      "price": "48000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115045285_1_1578509842_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "늑대와향신료 늑대와향신료키링 호로",
      "uid": "3926534",
      "update_time": 1578509842,
      "used": 13,
      "imp_id": "99a55fdaed9b000006f7",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "라코스테 신사 장목 정장양말",
      "num_comment": "0",
      "num_faved": "3",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115045150",
      "price": "2500",
      "product_image": "https://media.stg-bunjang.co.kr/product/115045150_1_1578509306_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "라코스테 정장양말 신사양말 장목양말",
      "uid": "7480646",
      "update_time": 1578509248,
      "used": 2,
      "imp_id": "99a55fdaed9b000006f8",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": true,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신세계백화점 구매 지방시 정품 스타 반지갑",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115045139",
      "price": "244000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115045139_1_1578509194_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "지방시 구찌 루이비통 반지갑 교신",
      "uid": "8981661",
      "update_time": 1578509189,
      "used": 2,
      "imp_id": "99a55fdaed9b000006f9",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "⚡️❗️신상❗베르사체스니커즈⚡️",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115045072",
      "price": "173000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115045072_1_1578508989_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "베르사체스니커즈 베르사체신발 베르사체신발추천 베르사체신발인기",
      "uid": "1376811",
      "update_time": 1578508980,
      "used": 2,
      "imp_id": "99a55fdaed9b000006fa",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "[정품]메타몽변신식스테일,쉐이미,잉어킹,엘풍,잠만보",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115045055",
      "price": "15000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115045055_1_1578509069_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "정품 인형 잠만보 포켓몬 포켓몬스터",
      "uid": "4896950",
      "update_time": 1578508925,
      "used": 2,
      "imp_id": "99a55fdaed9b000006fb",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "대성마이맥 신예은 노트 판매합니다.",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115045012",
      "price": "12000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115045012_1_1578508817_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "신예은공책 대성마이맥 신예은굿즈 신예은노트 노트",
      "uid": "6735598",
      "update_time": 1578508767,
      "used": 2,
      "imp_id": "99a55fdaed9b000006fc",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "아임낫어휴먼비잉 남방셔츠 (교신가능)",
      "num_comment": "2",
      "num_faved": "3",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115044683",
      "price": "20000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115044683_1_1578507566_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "아임낫어휴먼비잉 xl",
      "uid": "5095629",
      "update_time": 1578507566,
      "used": 13,
      "imp_id": "99a55fdaed9b000006fd",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "다이소 미니멜로우 폭신 스티커 일괄판매",
      "num_comment": "0",
      "num_faved": "1",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115044406",
      "price": "1800",
      "product_image": "https://media.stg-bunjang.co.kr/product/115044406_1_1578506684_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "다이소 미니멜로우 스티커 다이어리 씰스티커",
      "uid": "1319567",
      "update_time": 1578506649,
      "used": 13,
      "imp_id": "99a55fdaed9b000006fe",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "❤ 무스너클 19FW 쓰리쿼터 2019신규❤",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115044378",
      "price": "319000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115044378_1_1578506883_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "무스너클 무스너클쓰리쿼터 쓰리쿼터 버니스웨터 홉스엔샵",
      "uid": "7426033",
      "update_time": 1578506569,
      "used": 2,
      "imp_id": "99a55fdaed9b000006ff",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "이투스신승범 강한수학 수1확통(새교재)",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115044244",
      "price": "7000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115044244_1_1578506100_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "신승범 수학 이투스 강한수학 수1",
      "uid": "8160204",
      "update_time": 1578506100,
      "used": 2,
      "imp_id": "99a55fdaed9b00000700",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "[무신사구매]드로우핏 캐시미어 히든 싱글 코트[BLACK][L]",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115044195",
      "price": "150000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115044195_1_1578506011_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "코트 드로우핏 무신사 캐시미어 사이즈L",
      "uid": "1655685",
      "update_time": 1578505925,
      "used": 2,
      "imp_id": "99a55fdaed9b00000701",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "차스킨 콜라겐 앰플 (주름개선 기능성화장품) 최신제조상품",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115043974",
      "price": "65000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115043974_1_1578505932_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "앰플 주름개선 기능성화장품 주름앰플 미백앰플",
      "uid": "7077501",
      "update_time": 1578505359,
      "used": 2,
      "imp_id": "99a55fdaed9b00000702",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신상) 이중망사 플리츠 스커트",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115043787",
      "price": "18000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115043787_1_1578504957_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "망사스커트 롱스커트 이중망사스커트 플리츠스커트 러블리",
      "uid": "5878288",
      "update_time": 1578504940,
      "used": 2,
      "imp_id": "99a55fdaed9b00000703",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "아디다스 메신저 백",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115043679",
      "price": "20000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115043679_1_1578504728_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "아이다스 가방 메신저백 아디다스메신저백 아디다스가방",
      "uid": "6732228",
      "update_time": 1578504721,
      "used": 13,
      "imp_id": "99a55fdaed9b00000704",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신상) 아코디언 원피스",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115043549",
      "price": "32000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115043549_1_1578504455_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "세트원피스 아코디언원피스 미니원피스 55여성원피스 66여성원피스",
      "uid": "5878288",
      "update_time": 1578504428,
      "used": 2,
      "imp_id": "99a55fdaed9b00000705",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "해커스 신토익 보카+ETS 토익기출 VOCA",
      "num_comment": "0",
      "num_faved": "2",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115043535",
      "price": "19000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115043535_1_1578504406_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "해커스 보카 ETS보카 ETS토익기출보카 보카 voca",
      "uid": "3047636",
      "update_time": 1578504406,
      "used": 2,
      "imp_id": "99a55fdaed9b00000706",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "여다나 RC+LC+정재현 RC 속성노트+정재현 신토익 1000제 RC",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115043344",
      "price": "32000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115043344_1_1578534799_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "정재현 여다나 RC 1000제 속성노트",
      "uid": "3047636",
      "update_time": 1578504013,
      "used": 2,
      "imp_id": "99a55fdaed9b00000707",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": true,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "신품 매니퀸 가죽 벨트",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115043235",
      "price": "20000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115043235_1_1578503809_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "매니퀸 남성용벨트 가죽벨트 벨트",
      "uid": "301337",
      "update_time": 1578503809,
      "used": 13,
      "imp_id": "99a55fdaed9b00000708",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "[230] 블라이스 인형신발",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115043177",
      "price": "3000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115043177_1_1578503706_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "2802480",
      "update_time": 1578503706,
      "used": 13,
      "imp_id": "99a55fdaed9b00000709",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "[229] 블라이스 인형신발",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115043047",
      "price": "3000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115043047_1_1578503473_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "2802480",
      "update_time": 1578503473,
      "used": 13,
      "imp_id": "99a55fdaed9b0000070a",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "허바신 우타카밀 75ml",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115042851",
      "price": "3500",
      "product_image": "https://media.stg-bunjang.co.kr/product/115042851_1_1578503072_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "",
      "uid": "7003026",
      "update_time": 1578503072,
      "used": 2,
      "imp_id": "99a55fdaed9b0000070b",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "[XL] 무신사 스탠다드 숏패딩 18년형",
      "num_comment": "0",
      "num_faved": "1",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115042503",
      "price": "50000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115042503_1_1578502565_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "숏패딩 무신사 스탠다드 XL",
      "uid": "1032767",
      "update_time": 1578502417,
      "used": 13,
      "imp_id": "99a55fdaed9b0000070c",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "공무원 공부책 (재정국어,신용한행정학, 이병철904사회)",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115042337",
      "price": "30000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115042337_1_1578502137_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "재정국어 신용한행정학 신용한행정학개론 이병철904 공무원한국사교재",
      "uid": "4460051",
      "update_time": 1578502112,
      "used": 2,
      "imp_id": "99a55fdaed9b0000070d",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": false,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "방탄 앨범 / 럽욜셉 티어 / 포카, 등신대 포함!",
      "num_comment": "0",
      "num_faved": "1",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115042248",
      "price": "28000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115042248_1_1578502622_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "방탄 방탄소년단 방탄앨범 방탄포카 방탄소년단앨범",
      "uid": "6015768",
      "update_time": 1578501955,
      "used": 13,
      "imp_id": "99a55fdaed9b0000070e",
      "ad_ref": "",
      "faved": false
    },
    {
      "ad": false,
      "bizseller": false,
      "checkout": false,
      "contact_hope": false,
      "free_shipping": true,
      "is_adult": false,
      "is_super_up_shop": null,
      "location": "서울특별시 서초구 반포4동",
      "max_cpc": null,
      "name": "스피드 스케이트화 신발",
      "num_comment": "0",
      "num_faved": "0",
      "only_neighborhood": false,
      "outlink_url": "",
      "pid": "115042218",
      "price": "100000",
      "product_image": "https://media.stg-bunjang.co.kr/product/115042218_1_1578501904_w{res}.jpg",
      "pu_id": null,
      "ref_campaign": null,
      "ref_content": "",
      "ref_source": "",
      "status": "0",
      "style": "",
      "super_up": null,
      "tag": "스피드스케이트 신발 남자스키 스케이트화 스키",
      "uid": "3125345",
      "update_time": 1578501904,
      "used": 13,
      "imp_id": "99a55fdaed9b0000070f",
      "ad_ref": "",
      "faved": false
    }
  ],
  "specs": [
    
  ],
  "filters": {
    "q": "신"
  },
  "categories": [
    
  ],
  "recommended_categories": [
    
  ],
  "associate_keywords": [
    
  ],
  "n": 56,
  "num_found": 56,
  "redirect_uri": null,
  "shopingmoa_enable": false,
  "view_type": "3column_type_location",
  "flags": [
    {
      "type": "price",
      "label": "가격",
      "event_type": "flag_use_price"
    },
    {
      "type": "used_product",
      "label": "미개봉",
      "event_type": "flag_use_newproduct"
    },
    {
      "type": "free_delivery",
      "label": "무료배송",
      "event_type": "flag_use_freedelivery"
    },
    {
      "type": "neighborhood",
      "label": "내근처",
      "event_type": "flag_use_neighbor"
    }
  ]
}


// 자동완성 response (키워드: 신)
const auto_complete_res = {
	"result": "success",
	"keywords": [
		{
			"name": "교신"
		},
		{
			"name": "신발"
		},
		{
			"name": "런닝머신"
		},
		{
			"name": "메신저백"
		},
		{
			"name": "커피머신"
		},
		{
			"name": "신세계"
		}
	],
	"price_service": false
}